export const CLEAR_CREATE_HIRE_DATA = "CLEAR_CREATE_HIRE_DATA";
export const CREATE_HIRE_DATA_SELECT_GROUP = "LOOKUP_DATA_SELECT_GROUP";
export const CREATE_HIRE_DATA_SELECT_PRODUCT = "CREATE_HIRE_DATA_SELECT_PRODUCT";
export const CREATE_HIRE_DATA_CHANGE_FIELD = "CREATE_HIRE_DATA_CHANGE_FIELD";
export const CREATE_HIRE_DATA_UPDATE_PRODUCT_SELECTED = "CREATE_HIRE_DATA_UPDATE_PRODUCT_SELECTED";
export const CREATE_HIRE_DATA_SAVE_DATA_REQUEST = "CREATE_HIRE_DATA_SAVE_DATA_REQUEST";
