export const CORE_DATA_LOADINGS_STARED = "CORE_DATA_LOADINGS_STARED";
export const CORE_DATA_LOADING_FINISHED = "CORE_DATA_LOADING_FINISHED";
export const CORE_DATA_PLUS_COUNT = "CORE_DATA_PLUS_COUNT";
export const CORE_DATA_MINUS_COUNT = "CORE_DATA_MINUS_COUNT";
