export const LOOKUP_DATA_RESET = "LOOKUP_DATA_RESET";
export const LOOKUP_DATA_LOADINGS_STARED = "LOOKUP_DATA_LOADINGS_STARED";
export const LOOKUP_DATA_LOADING_FINISHED = "LOOKUP_DATA_LOADING_FINISHED";
export const LOOKUP_DATA_SELECT_GROUP = "LOOKUP_DATA_SELECT_GROUP";
export const LOOKUP_DATA_UPDATE_PRODUCT = "LOOKUP_DATA_UPDATE_PRODUCT";
export const LOOKUP_DATA_CHANGE_FIELD = "LOOKUP_DATA_CHANGE_FIELD";
export const LOOKUP_DATA_UPDATE_COLLECTIONS = "LOOKUP_DATA_UPDATE_COLLECTIONS";
